INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'06641962-5cb6-4ac0-9fa7-760a2a1dae1f', N'ari@yahoo.com', N'ARI@YAHOO.COM', N'ari@yahoo.com', N'ARI@YAHOO.COM', 0, N'AQAAAAIAAYagAAAAEBU8jm5idB0wadupBHAHEznarVCS7RL+zDiiziSxOorE635MxxaA+d+wWmCldPC2Lg==', N'YV7YP7P6B5JJDWQTMZZV53GEWZ6PGDN3', N'f2e829e7-73bf-4170-ba20-3fb934f3a866', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'129613c2-ad32-419e-b697-63d31d35ee04', N'ewf@fds', N'EWF@FDS', N'ewf@fds', N'EWF@FDS', 0, N'AQAAAAIAAYagAAAAEOaPUqTz9U7Vo6hHhs/6lZhsjpFzMelNxjgEDlobZegqlnovmU+CRg0jdbAH0vOgnA==', N'6D37NMQCQMCHV62JKE6T63DXAYOLW3ZC', N'665b358c-70c4-4cff-bd8f-688fe6e4ea93', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'26726b62-6766-44eb-a056-9bd3470024df', N'sasi@gmail.com', N'SASI@GMAIL.COM', N'sasi@gmail.com', N'SASI@GMAIL.COM', 0, N'AQAAAAIAAYagAAAAEMZI2iLrX7JqpBJdocevL0VrwczPFr5kn1p2m7kx2fb0EBlS/27vK3Zheznm2JdWEw==', N'SRVMXST6ENANKYYTDYOBQVC2YH5CLLE2', N'fcba9542-5df4-4ab2-b824-788271598086', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'270cb467-25c7-40c0-9d01-6331fbc0e70d', N'kannan@gmail.com', N'KANNAN@GMAIL.COM', N'kannan@gmail.com', N'KANNAN@GMAIL.COM', 0, N'AQAAAAIAAYagAAAAENEeeIlw59zvWbMAcdk/UMYsfbZSpkPoXlso0X5UAdMIto7XJV/y1vaC7IE5lrwszw==', N'6FTADPKC6FUUMFMBVJP7SLOX7XEDCR43', N'ce143a99-118a-45ad-ab7d-bff6ef86646c', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'55ea9b04-e9cd-4fcf-9ff2-8cbb7abffb44', N'Aridheena@gmail.com', N'ARIDHEENA@GMAIL.COM', N'Aridheena@gmail.com', N'ARIDHEENA@GMAIL.COM', 0, N'AQAAAAIAAYagAAAAEOVLN97FeosU8vwNPXWeAQD1yAhJ/PM1tF1OdQX7X8w6vYFyJM5AzPcW+0rjvtqJEg==', N'VJ6SSUYCUZSVXNQJYTRMI2W2D2AAPMWA', N'44584e80-4591-45da-aa80-323c82c19ca4', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'c63a2d16-c99f-41f6-8929-fd68e6762e31', N'arunsancha10@gmail.com', N'ARUNSANCHA10@GMAIL.COM', N'arunsancha10@gmail.com', N'ARUNSANCHA10@GMAIL.COM', 0, NULL, N'JBYSTRYLTVZHYT4D7PDTKNYDUF7YWN5F', N'9ad3f42c-6e78-474b-a9c8-f671dae2870b', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'ce4c9b16-08bf-4860-b099-f06957910303', N'ari@proton', N'ARI@PROTON', N'ari@proton', N'ARI@PROTON', 0, N'AQAAAAIAAYagAAAAEDKB0zPACVSXpjkajgVirl3zVEEvoAJPVL3DiMRCu2Symq0eVGpMtmdAk2FpdaLxig==', N'FYTJZO7QH5RMIFPCG3NJUTGFS4WKEHVG', N'9e8a4836-a9b1-4bb7-a99d-cc34cd84d9dc', NULL, 0, 0, NULL, 1, 0)
INSERT INTO [dbo].[AspNetUsers] ([Id], [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnd], [LockoutEnabled], [AccessFailedCount]) VALUES (N'd7c70f74-ed08-4089-91f8-176db07bd7a0', N'tariyanayagan@gmail.com', N'TARIYANAYAGAN@GMAIL.COM', N'tariyanayagan@gmail.com', N'TARIYANAYAGAN@GMAIL.COM', 1, NULL, N'TA7V5GNXBFK5GUK5NT74YEBTT5XV6Y73', N'd64b88dd-aedd-4d74-805a-ef8b6604b2fc', NULL, 0, 0, NULL, 1, 0)


Truncate Table 